#!/usr/bin/env bash
# Install the Dumont Secrets MCP locally, for the current user. Idempotent.
#
#   bash install-local.sh [--ref <branch|tag|sha>] [--repo <git url or path>] [--allow-unmerged]
#
# Refuses a commit that is not on the repository's main branch (checked with
# git merge-base --is-ancestor against a fresh fetch of main's history), so a
# pinned sha can only come from reviewed, merged code. --allow-unmerged (or
# DUMONT_SECRETS_ALLOW_UNMERGED=1) lifts that, for testing a branch or a PR.
#
# Fetches only mcp/ of the given ref (default main) from the public repository,
# builds it (npm ci with dev dependencies, tsc), prunes to production
# dependencies with --ignore-scripts, and installs it to
#   ~/.local/share/dumont-secrets-mcp/<sha>   with a `current` symlink,
# plus two small launchers in ~/.local/bin:
#   dumont-secrets-mcp      the stdio MCP server (register it in Claude Code / Dumont Code)
#   dumont-secrets-unlock   unlock your own vault for the MCP, in a terminal window
#
# It never installs the Bitwarden CLI, never logs in, never unlocks, never
# reads a secret, and never edits your Claude Code or opencode settings.
# Linux (WSL included) and macOS; Node >= 20.
set -euo pipefail

REF="${DUMONT_SECRETS_REF:-main}"
REPO="${DUMONT_SECRETS_REPO:-https://github.com/DumontAI/dumont-secrets.git}"
MAIN_BRANCH="main"
ALLOW_UNMERGED="${DUMONT_SECRETS_ALLOW_UNMERGED:-0}"
while [ $# -gt 0 ]; do
  case "$1" in
    --allow-unmerged) ALLOW_UNMERGED=1; shift ;;
    --ref) REF="${2:?--ref needs a value}"; shift 2 ;;
    --ref=*) REF="${1#--ref=}"; shift ;;
    --repo) REPO="${2:?--repo needs a value}"; shift 2 ;;
    --repo=*) REPO="${1#--repo=}"; shift ;;
    -h|--help) sed -n '2,21p' "$0"; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; exit 64 ;;
  esac
done
case "$REF" in -*|*[!A-Za-z0-9._/-]*) echo "Invalid ref: $REF" >&2; exit 64 ;; esac

ROOT="$HOME/.local/share/dumont-secrets-mcp"
BIN_DIR="$HOME/.local/bin"
MARKER="# generated by dumont-secrets install-local.sh"

say() { printf '==> %s\n' "$1"; }
die() { printf 'dumont-secrets install: %s\n' "$1" >&2; exit "${2:-1}"; }

# --- prerequisites ---------------------------------------------------------
case "$(uname -s)" in Linux|Darwin) ;; *) die "unsupported OS $(uname -s): use Linux, WSL2 or macOS" 69 ;; esac
command -v git >/dev/null 2>&1 || die "git is required" 69
command -v node >/dev/null 2>&1 || die "Node.js >= 20 is required (node not found)" 69
command -v npm >/dev/null 2>&1 || die "npm is required" 69
NODE_BIN="$(command -v node)"
NODE_MAJOR="$("$NODE_BIN" -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 20 ] 2>/dev/null || die "Node.js >= 20 is required (found $("$NODE_BIN" -v))" 69
if ! command -v bw >/dev/null 2>&1; then
  die "the Bitwarden CLI (bw) is not installed. Install it first, e.g.:
    npm i -g @bitwarden/cli
then re-run this installer." 69
fi

# --- resolve the ref to a commit --------------------------------------------
# A branch wins over a tag of the same name; an annotated tag resolves to the
# commit it points at (its "^{}" line), not to the tag object.
if printf '%s' "$REF" | grep -Eq '^[0-9a-f]{40}$'; then
  SHA="$REF"
else
  # The "^{}" pattern must be asked for by name: a plain tag pattern does not list it.
  SHA="$(git ls-remote "$REPO" "refs/heads/$REF" "refs/tags/$REF" "refs/tags/$REF^{}" 2>/dev/null | awk -v h="refs/heads/$REF" -v t="refs/tags/$REF" '
    $2 == h { head = $1 }
    $2 == t "^{}" { peeled = $1 }
    $2 == t { tag = $1 }
    END { if (head != "") print head; else if (peeled != "") print peeled; else print tag }')"
  [ -n "$SHA" ] || die "could not resolve ref '$REF' in $REPO"
fi
TARGET="$ROOT/$SHA"

# True when $SHA is on $MAIN_BRANCH of $REPO (a fresh fetch of main's commits only).
is_merged() {  # $1 git dir
  git -C "$1" fetch -q --filter=tree:0 origin "+refs/heads/$MAIN_BRANCH:refs/remotes/origin/$MAIN_BRANCH" 2>/dev/null ||
    git -C "$1" fetch -q origin "+refs/heads/$MAIN_BRANCH:refs/remotes/origin/$MAIN_BRANCH" ||
    die "could not fetch $MAIN_BRANCH from $REPO"
  git -C "$1" cat-file -e "$SHA^{commit}" 2>/dev/null &&
    git -C "$1" merge-base --is-ancestor "$SHA" "refs/remotes/origin/$MAIN_BRANCH"
}

mkdir -p "$ROOT" "$BIN_DIR"
INSTALLED_AS="$(cat "$TARGET/.complete" 2>/dev/null || true)"
if [ "$INSTALLED_AS" = "$SHA merged" ] || { [ "$ALLOW_UNMERGED" = 1 ] && [ -n "$INSTALLED_AS" ]; }; then
  say "Dumont Secrets MCP $SHA already installed"
else
  say "Fetching mcp/ at $REF ($SHA)"
  WORK="$(mktemp -d "$ROOT/.build.XXXXXX")"
  trap 'rm -rf -- "$WORK"' EXIT
  git -C "$WORK" init -q src
  git -C "$WORK/src" remote add origin "$REPO"
  git -C "$WORK/src" config core.sparseCheckout true
  printf '/mcp/\n' > "$WORK/src/.git/info/sparse-checkout"
  if is_merged "$WORK/src"; then
    MERGED=merged
    git -C "$WORK/src" checkout -q "$SHA"
  elif [ "$ALLOW_UNMERGED" = 1 ]; then
    MERGED=unmerged
    say "WARNING: $SHA is not on $MAIN_BRANCH of $REPO; installing it anyway (--allow-unmerged)"
    # A sha is fetched as itself; a branch or tag by name, then checked against the resolved sha.
    git -C "$WORK/src" fetch -q --depth 1 --filter=blob:none origin "$REF" 2>/dev/null ||
      git -C "$WORK/src" fetch -q --depth 1 origin "$REF"
    git -C "$WORK/src" checkout -q FETCH_HEAD
  else
    die "refusing $REF ($SHA): it is not on $MAIN_BRANCH of $REPO. Only merged code is installed;
  use --allow-unmerged (or DUMONT_SECRETS_ALLOW_UNMERGED=1) to test an unmerged commit." 65
  fi
  [ "$(git -C "$WORK/src" rev-parse HEAD)" = "$SHA" ] || die "$REF moved while installing (expected $SHA); re-run"
  [ -f "$WORK/src/mcp/package-lock.json" ] || die "$REF has no mcp/package-lock.json"

  say "Building (npm ci, tsc)"
  (
    cd "$WORK/src/mcp"
    npm ci --no-audit --no-fund --ignore-scripts --loglevel=error
    npm run --silent build
    rm -rf node_modules
    npm ci --omit=dev --no-audit --no-fund --ignore-scripts --loglevel=error
  ) || die "build failed"

  mkdir -p "$WORK/out"
  for entry in dist node_modules package.json package-lock.json README.md mcp.example.json; do
    [ -e "$WORK/src/mcp/$entry" ] && cp -R "$WORK/src/mcp/$entry" "$WORK/out/"
  done
  printf '%s %s\n' "$SHA" "$MERGED" > "$WORK/out/.complete"
  rm -rf -- "$TARGET"
  mv "$WORK/out" "$TARGET"
  rm -rf -- "$WORK"
  trap - EXIT
fi

# --- switch `current`, keep the previous one for rollback -------------------
if [ -L "$ROOT/current" ]; then
  OLD="$(basename "$(readlink "$ROOT/current")")"
  if [ "$OLD" != "$SHA" ]; then ln -sfn "$OLD" "$ROOT/previous"; fi
fi
ln -sfn "$SHA" "$ROOT/current"
KEEP_PREVIOUS="$( [ -L "$ROOT/previous" ] && basename "$(readlink "$ROOT/previous")" || true)"
for dir in "$ROOT"/*/; do
  name="$(basename "$dir")"
  printf '%s' "$name" | grep -Eq '^[0-9a-f]{40}$' || continue
  [ "$name" = "$SHA" ] || [ "$name" = "$KEEP_PREVIOUS" ] || rm -rf -- "$dir"
done

# --- launchers ---------------------------------------------------------------
# Launchers, not symlinks: an MCP client started from a desktop app often has no
# nvm/Homebrew PATH, so the node that passed the version check is pinned here
# (with a fallback to `node` on PATH if that one is removed later). Paths are
# written with printf %q, so any character in them stays one bash word.
write_launcher() {  # $1 name, $2 script under dist/
  target="$BIN_DIR/$1"
  if [ -e "$target" ] && ! grep -qF "$MARKER" "$target" 2>/dev/null; then
    die "$target exists and was not written by this installer; move it away and re-run" 73
  fi
  tmp="$(mktemp "$BIN_DIR/.$1.XXXXXX")"
  {
    printf '#!/bin/bash\n%s\n' "$MARKER"
    printf 'NODE=%q\n' "$NODE_BIN"
    printf 'SCRIPT=%q\n' "$ROOT/current/dist/$2"
    # shellcheck disable=SC2016 # written literally into the launcher
    printf '[ -x "$NODE" ] || NODE=node\nexec "$NODE" "$SCRIPT" "$@"\n'
  } > "$tmp"
  chmod 755 "$tmp"
  mv -f "$tmp" "$target"
}
write_launcher dumont-secrets-mcp stdio.js
write_launcher dumont-secrets-unlock unlock.js

say "Installed Dumont Secrets MCP $SHA"
say "  $BIN_DIR/dumont-secrets-mcp"
say "  $BIN_DIR/dumont-secrets-unlock"
case ":$PATH:" in *":$BIN_DIR:"*) ;; *) say "NOTE: $BIN_DIR is not on your PATH; add it to run dumont-secrets-unlock by name." ;; esac
cat <<EOF

Next steps (once per machine, in your own terminal):
  bw config server https://secret.getdumont.ai
  bw login <your email>          # email + master password (bw login --sso: Dumont SSO, not yet tested)
  dumont-secrets-unlock          # per session, in a terminal window; default 2h, --lock to end early

Optional, per machine: dumont-secrets-unlock --setup-auto stores your master password in the
OS credential store so the MCP unlocks by itself. RISK: then any program running as you (an AI
agent's shell included) can unlock your whole vault, personal items included, at any time.
Off by default; see the README section "Auto-unlock (opt-in)"; undo with --disable-auto.

Register the MCP:
  Claude Code:   claude mcp add -s user dumont-secrets -- $BIN_DIR/dumont-secrets-mcp
  opencode / Dumont Code (opencode.jsonc, under "mcp"):
    "dumont-secrets": { "type": "local", "command": ["$BIN_DIR/dumont-secrets-mcp"], "enabled": true }

Claude Code permissions: add these yourself to ~/.claude/settings.json (this
installer does not edit it). "ask" makes every value-returning or writing call
prompt even if the server is allowed ("ask" is checked before "allow"); "deny"
keeps Claude Code's Read, Grep and Glob tools (and its best-effort checks of
cat/head/tail) away from the session file. Neither stops a script the agent runs.
  "permissions": {
    "ask": ["mcp__dumont-secrets__secrets_get_secret",
            "mcp__dumont-secrets__secrets_generate_secret",
            "mcp__dumont-secrets__secrets_set_secret"],
    "deny": ["Read(//run/user/*/dumont-secrets/**)",
             "Read(~/.cache/dumont-secrets/**)",
             "Read(~/Library/Caches/dumont-secrets/**)"]
  }
Do not add those three tools to an allow list.

Optional scope file: ~/.config/dumont-secrets/mcp.json (see $ROOT/current/mcp.example.json).
secrets_get_secret stays disabled until you set value_collections there.
EOF
